name: 'anka-actions-up'
description: 'Spins up new Anka VM Instance through your Anka Build Cloud Controller.'
author: 'Veertu Inc.'
inputs:
  # Github
  gh-owner:
    description: 'GitHub repository owner'
    required: false
    default: ${{ github.repository_owner }}
  gh-repository:
    description: 'GitHub repository the github action runner will be attached to'
    required: false
    default: ${{ github.repository }}
  gh-pat:
    description: 'GitHub personal access token (requires "repo" scope access)'
    required: true

  # Template
  template-id:
    description: 'UUID of the Anka VM Template in the Anka Build Cloud Registry'
    required: true
  template-tag:
    description: "Anka VM Template's Tag"
    required: false
  template-runner-dir:
    description: ''
    required: false
    default: '/Users/anka/actions-runner'

  # Connection
  controller-url:
    description: "The Anka Build Cloud Controller's URL to communicate with"
    required: true
  controller-root-token:
    description: "Anka Build Cloud Controller's Root Token used for authentication"
    required: false
  controller-tls-ca:
    description: "Anka Build Cloud Controller TLS certificate's CA (needed if controller TLS cert is self-signed)"
    required: false
  controller-https-skip-cert-verify:
    description: "Skip the Anka Build Cloud Controller's TLS certificate verification"
    required: false
    default: 'false'
  controller-auth-cert:
    description: "Certificate to use for communication with the Anka Build Cloud Controller's Cert Auth feature"
    required: false
  controller-auth-cert-key:
    description: "Private key to use for communication with the Anka Build Cloud Controller's Cert Auth feature"
    required: false
  controller-auth-cert-passphrase:
    description: "The Auth Certificate's passphrase"
    required: false

  # Timeouts
  controller-http-poll-delay:
    description: "Delay (in seconds) between the HTTP requests to the Anka Build Cloud Controller's API"
    required: false
    default: '5'
  hard-timeout:
    description: 'TTL (in seconds) after which job will be forced to stop (fails with an error)'
    required: false
    # 12 hours
    default: '43200'

  # VM instance
  group-id:
    description: 'Anka Node Group ID (not name)'
    required: false
  node-id:
    description: 'Anka Node ID (not name)'
    required: false
  vcpu:
    description: 'The vCPUs to set before starting the Anka VM'
    required: false
  vram:
    description: 'The ram to set before starting the Anka VM'
    required: false

outputs:
  action-id:
    description: 'This is a unique action identifier, it will be set as an External ID in the VM and also as a label on the created Github action runner'
runs:
  using: 'node16'
  main: 'dist/index.js'
